// Mocks generated by Mockito 5.4.4 from annotations
// in smatch_badminton/test/widgets/provider_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smatch_badminton/models/api_response.dart' as _i4;
import 'package:smatch_badminton/models/availability.dart' as _i3;
import 'package:smatch_badminton/models/court.dart' as _i2;
import 'package:smatch_badminton/models/search_suggestion.dart' as _i8;
import 'package:smatch_badminton/repositories/court_repository.dart' as _i5;
import 'package:smatch_badminton/services/court_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCourt_0 extends _i1.SmartFake implements _i2.Court {
  _FakeCourt_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourtAvailability_1 extends _i1.SmartFake
    implements _i3.CourtAvailability {
  _FakeCourtAvailability_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResponse_2<T> extends _i1.SmartFake
    implements _i4.ApiResponse<T> {
  _FakeApiResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CourtRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourtRepository extends _i1.Mock implements _i5.CourtRepository {
  MockCourtRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set selectedCourt(_i2.Court? _selectedCourt) => super.noSuchMethod(
        Invocation.setter(
          #selectedCourt,
          _selectedCourt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.Court> get cachedCourts => (super.noSuchMethod(
        Invocation.getter(#cachedCourts),
        returnValue: <_i2.Court>[],
      ) as List<_i2.Court>);

  @override
  _i6.Future<List<_i2.Court>> fetchCourts({
    int? page = 1,
    int? limit = 10,
    String? district,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCourts,
          [],
          {
            #page: page,
            #limit: limit,
            #district: district,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i6.Future<List<_i2.Court>>.value(<_i2.Court>[]),
      ) as _i6.Future<List<_i2.Court>>);

  @override
  _i6.Future<_i2.Court> fetchCourtById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchCourtById,
          [id],
        ),
        returnValue: _i6.Future<_i2.Court>.value(_FakeCourt_0(
          this,
          Invocation.method(
            #fetchCourtById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Court>);

  @override
  _i6.Future<List<_i2.Court>> fetchNearbyCourts({
    required double? latitude,
    required double? longitude,
    double? radius = 5.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNearbyCourts,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
          },
        ),
        returnValue: _i6.Future<List<_i2.Court>>.value(<_i2.Court>[]),
      ) as _i6.Future<List<_i2.Court>>);

  @override
  _i6.Future<_i3.CourtAvailability> fetchCourtAvailability({
    required String? courtId,
    required String? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCourtAvailability,
          [],
          {
            #courtId: courtId,
            #date: date,
          },
        ),
        returnValue:
            _i6.Future<_i3.CourtAvailability>.value(_FakeCourtAvailability_1(
          this,
          Invocation.method(
            #fetchCourtAvailability,
            [],
            {
              #courtId: courtId,
              #date: date,
            },
          ),
        )),
      ) as _i6.Future<_i3.CourtAvailability>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CourtService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourtService extends _i1.Mock implements _i7.CourtService {
  MockCourtService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ApiResponse<List<_i2.Court>>> getCourts({
    int? page = 1,
    int? limit = 10,
    String? district,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourts,
          [],
          {
            #page: page,
            #limit: limit,
            #district: district,
          },
        ),
        returnValue: _i6.Future<_i4.ApiResponse<List<_i2.Court>>>.value(
            _FakeApiResponse_2<List<_i2.Court>>(
          this,
          Invocation.method(
            #getCourts,
            [],
            {
              #page: page,
              #limit: limit,
              #district: district,
            },
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<List<_i2.Court>>>);

  @override
  _i6.Future<_i4.ApiResponse<_i2.Court>> getCourtById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourtById,
          [id],
        ),
        returnValue: _i6.Future<_i4.ApiResponse<_i2.Court>>.value(
            _FakeApiResponse_2<_i2.Court>(
          this,
          Invocation.method(
            #getCourtById,
            [id],
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<_i2.Court>>);

  @override
  _i6.Future<_i4.ApiResponse<List<_i2.Court>>> getNearbyCourts({
    required double? latitude,
    required double? longitude,
    double? radius = 5.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyCourts,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
          },
        ),
        returnValue: _i6.Future<_i4.ApiResponse<List<_i2.Court>>>.value(
            _FakeApiResponse_2<List<_i2.Court>>(
          this,
          Invocation.method(
            #getNearbyCourts,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
            },
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<List<_i2.Court>>>);

  @override
  _i6.Future<_i4.ApiResponse<_i2.Court>> createCourt(_i2.Court? court) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCourt,
          [court],
        ),
        returnValue: _i6.Future<_i4.ApiResponse<_i2.Court>>.value(
            _FakeApiResponse_2<_i2.Court>(
          this,
          Invocation.method(
            #createCourt,
            [court],
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<_i2.Court>>);

  @override
  _i6.Future<_i4.ApiResponse<_i2.Court>> updateCourt(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCourt,
          [
            id,
            updates,
          ],
        ),
        returnValue: _i6.Future<_i4.ApiResponse<_i2.Court>>.value(
            _FakeApiResponse_2<_i2.Court>(
          this,
          Invocation.method(
            #updateCourt,
            [
              id,
              updates,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<_i2.Court>>);

  @override
  _i6.Future<_i4.ApiResponse<void>> deleteCourt(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCourt,
          [id],
        ),
        returnValue:
            _i6.Future<_i4.ApiResponse<void>>.value(_FakeApiResponse_2<void>(
          this,
          Invocation.method(
            #deleteCourt,
            [id],
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<void>>);

  @override
  _i6.Future<_i4.ApiResponse<_i3.CourtAvailability>> getCourtAvailability({
    required String? courtId,
    required String? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourtAvailability,
          [],
          {
            #courtId: courtId,
            #date: date,
          },
        ),
        returnValue: _i6.Future<_i4.ApiResponse<_i3.CourtAvailability>>.value(
            _FakeApiResponse_2<_i3.CourtAvailability>(
          this,
          Invocation.method(
            #getCourtAvailability,
            [],
            {
              #courtId: courtId,
              #date: date,
            },
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<_i3.CourtAvailability>>);

  @override
  _i6.Future<_i4.ApiResponse<List<_i8.SearchSuggestion>>> getAutocomplete({
    required String? query,
    int? limit = 10,
    bool? includeDetails = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutocomplete,
          [],
          {
            #query: query,
            #limit: limit,
            #includeDetails: includeDetails,
          },
        ),
        returnValue:
            _i6.Future<_i4.ApiResponse<List<_i8.SearchSuggestion>>>.value(
                _FakeApiResponse_2<List<_i8.SearchSuggestion>>(
          this,
          Invocation.method(
            #getAutocomplete,
            [],
            {
              #query: query,
              #limit: limit,
              #includeDetails: includeDetails,
            },
          ),
        )),
      ) as _i6.Future<_i4.ApiResponse<List<_i8.SearchSuggestion>>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
