org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Mapbox download token (public token for downloading SDK)
# Get your token from https://account.mapbox.com/access-tokens/
# SDK_REGISTRY_TOKEN=YOUR_MAPBOX_SECRET_TOKEN
