// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaCw_w_HLTDzHFm6bOL5j6Em86ScYyMjQ',
    appId: '1:286209752410:web:62a471ad02917928a18763',
    messagingSenderId: '286209752410',
    projectId: 'smatch-badminton',
    authDomain: 'smatch-badminton.firebaseapp.com',
    storageBucket: 'smatch-badminton.firebasestorage.app',
    measurementId: 'G-HTLS0TLJKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQWxEJkGHagw-ZuJaFnUWYaoWdmNVpVs',
    appId: '1:286209752410:android:8559399e5d6ca2d6a18763',
    messagingSenderId: '286209752410',
    projectId: 'smatch-badminton',
    storageBucket: 'smatch-badminton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Hno5eF9H96h8-L_LaQ6fcNCd6CTPhzc',
    appId: '1:286209752410:ios:e93e540a72486a07a18763',
    messagingSenderId: '286209752410',
    projectId: 'smatch-badminton',
    storageBucket: 'smatch-badminton.firebasestorage.app',
    iosBundleId: 'com.example.arcBadminton',
  );
}
