// Mocks generated by Mockito 5.4.6 from annotations
// in smatch_badminton/test/view_models/booking_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smatch_badminton/models/availability.dart' as _i3;
import 'package:smatch_badminton/models/court.dart' as _i2;
import 'package:smatch_badminton/repositories/court_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCourt_0 extends _i1.SmartFake implements _i2.Court {
  _FakeCourt_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourtAvailability_1 extends _i1.SmartFake
    implements _i3.CourtAvailability {
  _FakeCourtAvailability_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourtRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourtRepository extends _i1.Mock implements _i4.CourtRepository {
  MockCourtRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Court> get cachedCourts =>
      (super.noSuchMethod(
            Invocation.getter(#cachedCourts),
            returnValue: <_i2.Court>[],
          )
          as List<_i2.Court>);

  @override
  set selectedCourt(_i2.Court? court) => super.noSuchMethod(
    Invocation.setter(#selectedCourt, court),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i2.Court>> fetchCourts({
    int? page = 1,
    int? limit = 10,
    String? district,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCourts, [], {
              #page: page,
              #limit: limit,
              #district: district,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i5.Future<List<_i2.Court>>.value(<_i2.Court>[]),
          )
          as _i5.Future<List<_i2.Court>>);

  @override
  _i5.Future<_i2.Court> fetchCourtById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCourtById, [id]),
            returnValue: _i5.Future<_i2.Court>.value(
              _FakeCourt_0(this, Invocation.method(#fetchCourtById, [id])),
            ),
          )
          as _i5.Future<_i2.Court>);

  @override
  _i5.Future<List<_i2.Court>> fetchNearbyCourts({
    required double? latitude,
    required double? longitude,
    double? radius = 5.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNearbyCourts, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
            }),
            returnValue: _i5.Future<List<_i2.Court>>.value(<_i2.Court>[]),
          )
          as _i5.Future<List<_i2.Court>>);

  @override
  _i5.Future<_i3.CourtAvailability> fetchCourtAvailability({
    required String? courtId,
    required String? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCourtAvailability, [], {
              #courtId: courtId,
              #date: date,
            }),
            returnValue: _i5.Future<_i3.CourtAvailability>.value(
              _FakeCourtAvailability_1(
                this,
                Invocation.method(#fetchCourtAvailability, [], {
                  #courtId: courtId,
                  #date: date,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.CourtAvailability>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
