// Mocks generated by Mockito 5.4.6 from annotations
// in smatch_badminton/test/view_models/payment_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smatch_badminton/models/booking.dart' as _i2;
import 'package:smatch_badminton/models/payment.dart' as _i3;
import 'package:smatch_badminton/services/payment_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBooking_0 extends _i1.SmartFake implements _i2.Booking {
  _FakeBooking_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatePaymentResponse_1 extends _i1.SmartFake
    implements _i3.CreatePaymentResponse {
  _FakeCreatePaymentResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayment_2 extends _i1.SmartFake implements _i3.Payment {
  _FakePayment_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i4.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.PaymentNotification> get notificationStream =>
      (super.noSuchMethod(
            Invocation.getter(#notificationStream),
            returnValue: _i5.Stream<_i3.PaymentNotification>.empty(),
          )
          as _i5.Stream<_i3.PaymentNotification>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i5.Future<_i2.Booking> createBooking(_i2.CreateBookingRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [request]),
            returnValue: _i5.Future<_i2.Booking>.value(
              _FakeBooking_0(
                this,
                Invocation.method(#createBooking, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.Booking>);

  @override
  _i5.Future<_i3.CreatePaymentResponse> createPayment(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#createPayment, [bookingId]),
            returnValue: _i5.Future<_i3.CreatePaymentResponse>.value(
              _FakeCreatePaymentResponse_1(
                this,
                Invocation.method(#createPayment, [bookingId]),
              ),
            ),
          )
          as _i5.Future<_i3.CreatePaymentResponse>);

  @override
  _i5.Future<_i3.Payment> getPayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPayment, [paymentId]),
            returnValue: _i5.Future<_i3.Payment>.value(
              _FakePayment_2(this, Invocation.method(#getPayment, [paymentId])),
            ),
          )
          as _i5.Future<_i3.Payment>);

  @override
  _i5.Future<_i3.Payment> queryPaymentStatus(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#queryPaymentStatus, [paymentId]),
            returnValue: _i5.Future<_i3.Payment>.value(
              _FakePayment_2(
                this,
                Invocation.method(#queryPaymentStatus, [paymentId]),
              ),
            ),
          )
          as _i5.Future<_i3.Payment>);

  @override
  _i5.Future<_i2.Booking> getBooking(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBooking, [bookingId]),
            returnValue: _i5.Future<_i2.Booking>.value(
              _FakeBooking_0(this, Invocation.method(#getBooking, [bookingId])),
            ),
          )
          as _i5.Future<_i2.Booking>);

  @override
  _i5.Future<void> connectAndSubscribe(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#connectAndSubscribe, [paymentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void sendPing() => super.noSuchMethod(
    Invocation.method(#sendPing, []),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribe() => super.noSuchMethod(
    Invocation.method(#unsubscribe, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
